[project]
name = "sudoku-solver"
version = "0.1.0"
description = ""
authors = [
    {name = "jiaquan-cheng",email = "j.q.cheng@icloud.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "z3-solver (>=4.16.0.0,<5.0.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
solve = "sudoku_solver.solver:main"
[dependency-groups]
dev = [
    "pytest (>=9.0.3,<10.0.0)"
]
